* Metro
:PROPERTIES:
:header-args: :tangle ~/dev/projects/quest/metro/metro.fountain
:END:

#+begin_src fountain
  THE DMZ.


  A city in turmoil. Simultaneously in mourning and furiously
  looking for an answer.

  The loss of a cultural icon, the touchstone of civil society
  in the metro. DWAYNE THE IRAQ JOHNSON. A man whose death has
  catapulted the once peacful city into riotous anger.

  Both sides of the DMZ have been shaken to their core. Who
  killed him? Why?

  There are talks of war...
#+end_src

** Locations
*** The DMZ
**** The Underground
***** Locations
****** The Bar
**** Katya's Home
**** Shaggy's Sandwich Shack
**** Mall
**** The Police Station
**** Honolulu Hawaiian's Bar
**** The Slums
**** The Bazaar
** Quests
*** A Lost Boy

#+begin_src fountain
# A Lost Boy
#+end_src

**** Characters

- [[*Katya][Katya]]
- [[*Delvin][Delvin]]
- [[*Peter][Peter]]
- [[*Jed][Jed]]
- [[*Larissa][Larissa]]

**** Locations

- [[*The Bar][The Underground Bar]]
- [[*Katya's Home][Katya's Home]]
- [[*Honolulu Hawaiian's Bar][Honolulu Hawaiian's Bar]]

**** Steps
***** 1. A Mother In Pain

The beginning of the Metro Reboot. Recapping the events of
the previous season and laying the foundation for the
conflict that is to come.

I really need to establish how important Dwayne was to the
rest to the DMZ since its going play a major role down the
road.

#+begin_src fountain
  ## A Mother In Pain

  INT. HONOLULU HAWAIIAN'S BAR - EAVENING #1A#

  The once boisterous bar is now silet except for the
  grumblings of a few downtrodden patrons. HAWAIIAN'S vibrant
  and colorful aesthetic doesn't seem to have the same appeal
  under the circumstances.

  A lonesome woman, KATYA, sits apart from the rest of the
  patrons. Her long ragged hair and longing stare gives her
  away as a mother in pain.

  THE PARTY enters the bar. A band of oportunists, thrill
  seekers, schemers, or people looking to do the right thing
  we don't know. They orient themselves and make their way to
  their next client. They're here to find a her son, why hes
  missing and how it came to be, they have yet to know. Only
  KATYA can say.

#+end_src

****** Introduction

#+begin_src fountain

  THE PARTY
  ,*Introduces themselves and asks her what the job is.*

  KATYA
  My boy, hes gone. Its been three days and the station police
  don't care.
  They're so busy with _DWAYNE_, but he's my son, hes all I
  have left.

#+end_src

****** Regarding What Happened

  #+begin_src fountain

    KATYA
    Three days ago, I found his bed empty. It was the fourth
    time this month hes done this. He, and his *friend* JED
    always come back the next day covered with grime and dust
    from the tunnels. I know he went artifact hunting, I just
    do. Hes been talking about it for weeks.

  #+end_src

****** Regarding Payment

#+begin_src fountain

  KATYA
  I don't have much to spare, just a few rounds to go between
  you. I do have my husband's old rifle, which I would be
  willing to part with if I can see my boy again. It got him
  through the last war and his years as a STALKER. At least
  until it didn't.

#+end_src

****** Regarding Why He Went Into The Tunnels

#+begin_src fountain

    KATYA
  My husband OMAR was a stalker. one of the best, but a few
  months back a controller took him from us. PETER hasn't
  taken it well. He's been trying to become a STALKER himself,
  but he just doesn't have the heart for it.
  Its that boy JED, whose convinced him that if he somehow
  brings back an artifact the STALKERS will let him join.
  Ridiculous, I know, but he's a boy and it gives him _hope_.

#+end_src

****** Regarding Possible Leads

#+begin_src fountain

  KATYA
  I'm not sure. My husband never talked about his work at
  home, he left that for the other STALKERS. Maybe DEVLIN can
  help, my husband and him go way back.
  PETER kept all the things he found in the tunnels. I can
  show you his room, maybe that will help?

#+end_src

***** 2. The Long Walk

The party is venturing forth into the tunnels in search of
Peter, guided by Larissa they make their way to Debrovka
Station.

The Party will have to choose between going through the
maintenance tunnels which will be an exercise in overcomming
madness or fighting/sneaking through a bandit camp.

This section will encompass the events leading up to that
fork in the road and the discussion about which they pick.

- Location :: Tunnels

#+begin_src fountain
  ## The Long Walk

  EXT. TUNNELS #1B#

  The Party begins their long quest to Debrovka Station. The
  journey only made possible by their stalwart guide Larissa,
  navigating every abandoned station, wading through every
  flooded maintenance bay, and avoiding every mutated
  monstosity the tunnels can throw at you.

  At every turn a new danger, a perpetual darkness at the end
  of every tunnel, watching, waiting, for its next victim to
  fall into its gloomy depths.
#+end_src

***** 3. Wading Through Memories
If the player's decide to make their way through the
maintenance tunnels, which looks to be the way Jed and Peter
went, they will have to contend with the ghosts of the
engineering team that used to work there.

I'm planning on this section to be mostly about will saves
and madness effects, being inspired heavily by the valve
scene from /Chernobyl/.

#+begin_src fountain
## Wading Through Memories
#+end_src

****** Music

- [[https://open.spotify.com/track/0aud7NouD28YTcD7WJzioD?si=8NBmnrQySfKBQyrqc_mlRQ][The Door]] (High Madness)
- [[https://open.spotify.com/track/4f76tcz3PKwty5QVA8JVCA?si=413VVlP8TbGQi1tIsv1YgA][Cooridors]] (Medium Madness)
- [[https://open.spotify.com/track/1cS7AxpJiwDhCh7v2B0LRd?si=MTATU3ICSuqD3devF-kqxw][Turbine Hall]] (Low Madness)

****** Layout

    #+begin_src artist :tangle no


                                         /----------+---------------+---+     .
                                      /--           |  stair down   |   |  .-+ m  ..
                                    /-      /-------+---------------+   +   .. -mm+   .
      +---------+                 --    /---             +---+-----++   +--+-#%+%%%.--.
      |entrance |                |    --                 | stairs  |      +..-%%#%m#- .
      +-----+   +                /   /                   +   +-----+       ..---m+.-. -
            |   |               /   /                    |   |             . .-.-..  .  +---+---+
            |   +               |   |                    |   |                 ..+|     | exit  |
            |   |          +----+   +----m .-. --.  +----+   +                    |     |   +---+
            |   |          |             | ..-.. +  |        |                    |     |   |
            |   +----------+            .%+*%%#m+m+-+ control| generator room     |     |   |
            |                            .m#+###+#+ - room   |                +---+-----+   |
            ++--+----------+            .m+m#m*+#++-+        |                |             |
                           |             -.---%m.  .+        +                |   +-----+---+
                           +----+   +----+-.. + .   +----+---+                |   |
                                |   |                    |     broken ladder  |   |
                                +   +                    |         +---+      |   |
                                |   +---------+          |       +-+---+------+   +
                                |             |          |       |     catwalk    |
                                +---+-----+   +          +-------+----------------+
                                          |   |
                                          |   |
                         +----------------+   +
                         |                    |
                         |                    |
                         |      barracks      |
                         |                    |
                         |                    |
                         +--------------------+

    #+end_src

****** Madness Events
******** The Wrench

#+begin_src fountain
  INT. GENERATOR BAY HUB #1C1#

  PC begins to make their way to the to the door, the sound of
  boots pushing through water echoing off the walls.

  PC's walk is interrupted when his boot strikes a metal
  object. Looking down he sees a large steel wrench, rusing
  away in the shallow water.

  Overcome by some indescribable urge, You reach into the
  murky water and retrieve the wrench. As you turn it over in
  your hands, the urge becomes a compulsion, a compulsion to
  get to work, its almost time for the shift change and your
  coworkers are depending on you.

  PC quickly snaps back to reality, dropping the wrench back
  into the water, it begins to sink, sink past the floor and
  into a deep dark abyss. Slowly glinting off your headlamp
  before finally disappearing into the blackness.
#+end_src

******** Crack In The Wall

#+begin_src fountain
  INT. GENERATOR BAY, BARRACKS #1C2#

  As PC makes their way down the row of abandoned bunks, a
  sliver of light catches their eye as it emanates from a
  crack in the wall.

  Approaching the light, your Geiger counter begins to tick,
  slowly at first, it quickly increases in intensity as your
  get closer. Standing in front of it now, the red light
  bathes your face in a warm glow. The Geiger counter now
  making a steady shrill screech.

  PC turns to the party motioning to the light, before turning
  back around to find the light has disappeared. No glow, no
  screeching Geiger counter, just a small crack in the cold
  concrete.
#+end_src

******** Change Of Scenery

#+begin_src fountain
INT. GENERATOR BAY #1C3#

#+end_src

******** Falling Off The Catwalk

#+begin_src fountain
INT. GENERATOR BAY #1C#


#+end_src

***** 3. Bandits

Gonna wing it lol

***** 4. The Station

This will mostly be a transition section to get the party
into the arcade. Probably will be mostly empty and lots of
descriptions of empty houses and displaced families.

Emphasis on the overwhelming silence.

This section will also include the party being sucked into
the XCOM arcade cabinet.

#+begin_src fountain
  ## The Station

  EXT. DEBROVKA STATION
#+end_src

***** 5. Vigilio, Confido

The Party will fight their way through a combat encounter
with sectoids and thinmen.

They'll be transported in on big sky and dropped into an
American city center to extract an HVT (Peter).

All damage in during the combat encounter will be real and
transfer over to their characters after the fight.

Peter also will not have any knowledge of who he is until
after he has been extracted and the party has exited the
cabinet.

The reward for completing the encounter will be an xcom pin.
It confers =Steadfast=: Never panic as a result of getting
wounded, allies panicking, allies getting wounded or killed,
or the intimidation ability.

Upon exist of the sky range the party will experience their
first earthquake signaling =The Collapse=.

#+begin_src fountain
  ## Infilitration

  You find yourself floating in space. Your surroundings a
  white grid going off in all directions toward infinity.
  Positioned directly across from one another, you feel
  yourself confined to a sitting position, strapped in to some
  invisible harness.

  Looking down you notice the world materializing below you
  one cell at a time, filling out each cell looks to be the
  tops of buildings. They quickly move past you and as more
  and more of the world materializes, you find yourself flying
  over a vast moonlit cityscape. Only once the last patch has been
  filled does a cabin begin to form around you

  INT. SKYRANGER - NIGHT

  Flooded with memories of past missions, you feel at ease
  inside the cabin of the =Sky Ranger=. Your dauntless pilot
  BIG SKY has pulled you out of many a hot evac, never once
  leaving the squad behind.

  Crackling over the intercom. Central Officer Bradford begins
  his briefing.

  CENTRAL OFFICE BRADFORD
  U.N. official PETER VAN DOOR and his entourage were caught
  in an explosion that decimated a nearby city block, and
  we're picking up hostiles converging in on the area. We need
  you to confirm Mr. Van Doorn is still alive, and bring him
  back safe before the whole place is overrun.

  The cabin light flashes and you are bathed in a red glow.
  The Crew Chief lifts his hand raising two fingers.

  CREW CHIEF
  TWO MINUTES!

  You release your harness, and retrieve your weapons. The
  sounds of magazines being loaded and bolts racked fills the
  cabin of the sky ranger.

  CREW CHIEF
  ONE MINUTE!

  Standing now you grab on to railing above you and face the
  rear of the sky ranger. The CREW CHIEF lowers the ramp,
  rooftops rushing past before melding back into the skyline.

  BIG SKY brings the sky ranger into a hard banking left turn,
  your body leaning into the turn, as he brings the aircraft
  in for a landing. The wheels of the sky ranger barely
  touching the ground before the CREW CHIEF waves you down the
  ramp.

  The LIGHT FLASHES GREEN.

  Sprinting down the ramp, you take up positions behind a
  burnt out police cruiser. BIG SKY lifting off to orbit the
  AO as quickly as he landed.
#+end_src
https://youtu.be/RdzpXmcLk-U?t=42

Van Doorn will be located in the back corner having
baricaded himself in an old office. He will start saying Van
Doorn's voice lines as the party gets near.

Van Doorn (Peter) Can only speak van doorn's voice lines,
and any attempt to ask him another question will result in
him saying another pre-canned voice line. from the following
list.

- "You the Ops team? Get over here!"
- "Get down here! Not fair if I have all the fun."
- "You coming down here or what?"
- "Come on! I won't go down without a fight."
- "Thank God you're here. I'm still breathing, but I
  can't say the same for a lot of my boys. Let's get out
  of here before any more of those things show up."
- "I don't know what outfit you're from, but I haven't
  seen gear like that before."
- "If we get out of here alive, I just hope I get
  another shot at these alien bastards... I owe it to my
  men."
- "I just wish I could have done more for my people, I
  lost some good men."
- "It was looking bad out there. I might not have made
  it if you didn't show up."
- "I owe you one... seriously... I wouldn't be here
  without your help."

****** *Post Exfil*
On mission complete, the squad will experience the world
dematerializing around them until they are standing in the
white void.

Once their they will see a mission complete screen and a
floating keyboard asking them to enter a name for the high
score board.

the board will have several names all with =DNF= as their
score. their names (if asked are)

- Ian Cognito
- Gurgglenoise
- Nachos Del Grande
- Crinkledink Whizzlefizz

#+begin_src fountain
  ## Exfiltration

  Strapped securely into your seats aboard the =Sky Ranger=,
  the dim lights of the cabin bring you comfort as BIG SKY
  sets course for home.

  It is in that moment, flying above that moonlit cityscape
  that the CREW CHIEF dematerializes before your eyes, quickly
  followed by BIG SKY. Left alone in the cabin of the =Sky
  Ranger= it's not long before the cabin dematerializes too.
  Strapped into an invisible harness, hurtling over rooftops,
  all the memories of past missions, friends back at base,
  your lives before XCOM, fade away, until all that's left is
  ... you.

  The world itself quickly follows suit, quickly replaced by a
  gridded grey room. The harness no longer holding you in
  place, you find yourselves standing before a massive
  floating monitor.

  CABINET
  MISSION COMPLETE!

  The words are quickly replaced by a prompt, a keyboard
  materializing in front of the party.

  CABINET
  HIGH SCORE: 13,029
  Enter name:

  (the party enters a name for the scoreboard)

  Exiting the high score screen, your vision begins to fade to
  black. When it returns, you are standing in front of the
  cabinet, your high score displayed prominently at the top.
  $(random party member), to your right a small child barely
  chest height is looking confusedly around the room.
#+end_src

Timmy will be generally confused, having no memory of the
encounter in the cabinet.

******* Do you remember what happened?
#+begin_src fountain
  TIMMY
  I don't know? I remember walking through the station,
  finding the cabinet and then PETER put the coin in the
  cabinet and, and, and that's it...

  TIMMY'S eyes go wide, he looks up at you frantically.

  TIMMY
  PETER! where's PETER!? He has to be here

  TIMMY begins madly looking about the room for signs of his
  friend. His eyes darting from you, to the cabinet, to other
  parts of the room. It's not long before his eyes fall to the
  frail lifeless legs of PETER peaking out from behind one of
  the turned over cabinets.

  TIMMY
  No No NO NO NO NO NO NO NO...

  He starts trying to push his way past you, to see his friend.
#+end_src

******* $(if the players try to prevent him from seeing the body)
#+begin_src fountain
  TIMMY
  PLEASE! I just want, I just...

  TIMMY looks up at you

  TIMMY
  He's my friend...

  his tiny body desperately tries to push past you. His
  eyes welling with tears. His attempts to push past
  growing weaker and weaker until it's barely a meek
  clawing. He collapses in your arms, his wails echoing off the
  walls of the long dead station. His tears soaking the
  cloth of your shirt.
#+end_src

******* $(if the players let him pass)
#+begin_src fountain
  You step aside, letting him have one last look at his friend
  before moving on.

  TIMMY scrambles past you, sprinting towards the back of the
  arcade. He comes to a stop just behind the turned over
  cabinet. All his frantic energy leaves his body as he stands
  still over what's left of his friend. Several minutes go by
  before TIMMY turns the body of his friend, having seen the
  fruits of all their childhood misdeeds vanish before his
  yes.

  TIMMY walks up to $(random party member). Gaze cast
  downward.

  TIMMY
  Can we go?
#+end_src

****** *After Exit*
The party will experience the first earth quake signaling
the coming collapse.

#+begin_src fountain
  Gathering yourselves, you turn and make your way out of the
  arcade. As you reach the threshold of the arcade, the floor
  beneath you begins to shake, then the walls, then the
  ceiling. Dust falling all around you, quickly followed by
  several loose ceiling tiles.

  As quickly the tremor came, it leaves. The only sign it ever
  having been there a few broken ceiling tiles and some extra
  dust on the dusty floor.
#+end_src

******* Mechanics
Combat will use my combat calculator in coordination with
roll20

*Characters*
*Thin Man*
Thin Men are unnervingly human-looking aliens who apparently
*serve as infiltrators for the invaders. They have short
*black hair and wear blue suits.

- /Acid Spit/ :: Reduces =aim= by 4 and =mobility= by a quarter.
- /Jumpy Legs/ :: Can leap to high ground.
- /Suppression/ :: Pin an enemy unit with withering fire.

*Sectoid*
Sectoids are weak and die quickly against experienced
soldiers, but are still dangerous early in the campaign.

- Suppression :: Pin an enemy unit with withering fire.
- Psy Panic :: Cause a unit to panic on their turn for 1-2
  turns.

*Assault*
CQC Specialist

- Run & Gun :: Allows firing or Overwatch after Dashing.
- Close Combat :: Specialist Confers a reaction shot against
  any enemy who closes to within 4 tiles. (Passive)

*Infantry*
Backbone of the infantry.

- Light 'Em Up :: Standard shots no longer end the turn, if
  taken as the first action.
- Covering Fire :: Overwatch can trigger on firing actions
  as well as movement. (Passive)
- Suppression :: Pin an enemy unit with withering fire.

*Gunner*
Heavy weapons specialist.

- Suppression :: Pin an enemy unit with withering fire.
- Holo-Targeting :: Shooting at or suppressing enemies
  confers +2 Aim to allies' attacks on those enemies until
  end of turn. (Passive)

*Sniper*
Long range specialist

- Squadsight :: Allows firing at targets in any allys sight
  radius within weapon range. (Passive)
- Low Profile :: Makes half cover grant full cover defensive
  bonus (Passive)

***** 6. Close Encounter Of A Third Kind

After recovering Peter, the party will encounter [[*Aion][Aeon]]
wandering the tunnels downtrodden at their failure to stop
this coming collapse.

Before they leave the party, they're gonna enlist the party
for help fighting the force that is drawing to destroy the
metro/humanity.

#+begin_src fountain
  ## Close Encounter Of A Third Kind

  In the distance the party hears a sound. A rock kicked.

  Looking in in that direction $(random party member), you see
  a woman meandering toward you, she seems lost, or not
  looking to be found? She has no belongings with her, just
  the clothes on her back. Clothes that seem distinctly clean
  for being in the metro. The same goes for her long brown
  hair, shining in the light of your headlamp.

  The woman kicks another rock haphazardly in your direction,
  not seeming to notice your presence. It tumbles down the
  tracks before softly bouncing off $(random party member)'s
  shoe.

  The woman stops, looking up she and seeing the party, she
  deflates, shoulders slumping and head falling.

  AEON (female)
  Oh... It's you...

  $(random party member), taking a step forward, he picks up
  the rock, looking it over briefly before flicking it at
  your face.

  AEON (male)
  I guess I should have seen this coming.
  Probability and all that...
#+end_src

****** If asked what the party did to earn AEON'S wrath
#+begin_src fountain
  AEON
  (scoffing)
  Oh, a great many things..

  In the blink of an eye, the $(random pronoun) has
  disappeared from view. You all take a step back,
  trying process what metro trickery this is.

  Vardan, startled by a sound coming from behind them.

  AEON
  BOOOO!!!!
  (laughing)
  (Deep sigh of satisfaction)

  Walking up beside Vardan, she puts a hand on your shoulder.

  AEON
  It's the little things that make it all worth it.
  Wouldn't you say so Vardan?
  or...
  or, was it MARK?
  You know, I can't remember anymore...

  Walking down the line they come up to DICK. Looking over
  this caricature of a man.

  AEON
  Never satisfied are we?
  Have you tried settling on just one?
  (leaning in closer)
  Or does the thought scare you more than you let on?

  Continuing down the line, they almost pass VINCENZO
  by without so much as a glance. Only after a few
  feet do they seem to realize that someone was actually
  standing there.

  AEON
  You...
  You are something new aren't you?
  I like new...

  The woman steps closer, invading your personal space. She
  brings her face with an inch of yours. Inspecting you as a
  child would a new doll.

  AEON
  We're going to have a lot of fun, I can tell.

  Finally coming up to RICKY PHOENIX, the man's average build
  standing in stark relief to RICKY'S wrestler body.

  AEON
  (staring at RICKY'S right hand)
  Given up the search haven't we?
  Or were you just bored?
  (laughing)

  The woman begins to cackle, keeling over trying to contain
  it. Obviously finding the whole situation unbearable funny.
#+end_src

****** If the party threatens AEON with violence
#+begin_src fountain
  You raise your weapon, trying to gain control over the
  situation rapidly deteriorating before you.

  AEON
  (starting to cry)
  Please, Please do it.
  I beg you.
  Let me sleep...

  The woman falls to her knees in front of you, tears
  streaming down her face. She reaches out pulling the barrel
  closer until its resting on her forehead.

  AEON
  Please...
#+end_src

******* If the party doesn't pull the trigger
#+begin_src fountain
  You deflate, unable to pull the trigger. The barrel of your
  gun slowly falling away from her forehead

  AEON
  Come on.
  Do it.
  (voice filling with disdain)
  DO IT

  She grabs the end of the gun forcing it back to her
  forehead.

  AEON
  WHAT ARE YOU WAITING FOR!

  She digs her head into the barrel, it leaves a mark. The
  woman looks up at you face filled with rage at your
  inaction.

  AEON
  Pathetic...

  She slaps the gun away and stands back up.
#+end_src

******* If the party does pull the trigger
#+begin_src fountain
  You pull the trigger, bracing for the recoil that never
  comes.

  In your hands, a harmless wooden broom.

  Standing now, the woman looks over your gun, somehow in her
  hands now.

  AEON
  Sometimes I forget how small you are...

  Barely having time to flinch, she brings the weapon to her
  shoulder and pulls the trigger.

  Your hands are halfway up to your face before you realize
  that the only thing that came out of the barel were a few
  delicate soap bubbles.

  AEON
  (laughing)

  Satisfied with the show, she tosses your weapon back to you.
#+end_src

****** If the party continues to ask who AEON is (or enough time has passed)
#+begin_src fountain
  AEON
  Me?

  Bristling at the question, the woman walk up to you.

  AEON
  I am...

  They snap their fingers. The person standing before you is
  no longer that young woman with beautiful long brown hair.
  They have been replaced by an elderly woman. Her face filled
  with grief, having seen many a tragedy in these tunnels.

  AEON
  Whoever..

  Snap! A grime covered young man, head buzzed short. The
  straps of his plate carrier digging into his skin. His eyes
  glazed over staring through you. How much war has this man
  seen?

  AEON
  I want...

  Snap! Another switch, but it doesn't stop with just one. A
  new person takes their place quickly, several a second now.
  A small child, an elderly man, a wounded stalker.
  Every face a new life, a new story. The pace quickens. It's
  overwhelming. So many lives, so much history flashing before
  your eyes.

  You take a step back unable to cope with what you're seeing.
  The flickering form of humanity follows you.

  AEON
  To be.

  A final snap of their fingers, before they seem to settle on
  the body of the young woman. Turning away from you.
  Satisfied at the display they've put on.
#+end_src
****** At the end of the encounter
#+begin_src fountain
  The world begins to violently shake. More violent than the
  last time, pieces of concrete falling from the ceiling. You
  scrambled out of the way of a few larger pieces.

  The woman doesn't seem to care. More saddened at having to
  stop playing than concerned about the concrete trying to
  impale them.

  The shaking subsides, several chunks of concrete littering
  the tunnel.

  AEON
  (sighing)
  Next time...

  The woman starts meandering down the tunnel. Seemingly
  content to resume wandering. Looking back over their
  shoulder at you.

  AEON
  Well, I hope I wont be seeing you...

  They take a another step down the tunnel before stopping.

  AEON
  Maybe...
  With more people?

  Turning around, they glace at the party.

  AEON
  I mean.
  I't can't hurt?
  Yea yea yea, okay.

  The woman turns back around quickly making their way down
  the tunnel, a little more purpose in their stride, before
  fading into the darkness of the tunnel.

  Alone now, a bit of moonlight shining through a new crack in
  the ceiling, you can't help but feel you've been volunteered
  for something.
#+end_src
***** 7. The First End

Upon returning from the tunnels and experiencing
increasingly violent earthquakes. The party will return
Peter to Katya.

At that moment a final, extremely energetic earthquake will
begin leading to chaos and falling debris as the DMZ begins
to tear apart.

Before it's complete destruction the party will see and
speak to Aion who will express excitement at seeing them
soon, just before they are taken by the destruction of the
earthquake.

The entire party dies and we end the session.

#+begin_src fountain
  ## The First End

  KATYA nearly faints at the sight of her son safe trailing
  behind you. They lock eyes, PETER runs into his mother's
  waiting arms.

  The sight brings a smile to DELVIN'S grizzled face. He looks
  at LARISSA, she shrugs and starts making her way to back to
  the underground bar.

  KATYA
  THANK YOU THANK YOU THANK YOU

  She goes in to hug you, but stops half way. thinking better
  of it. The results, a weird half hearted chest pat with a
  bit of straightening out the wrinkles in your clothes.
  Adorable in a way only a mother can pull off.

  KATYA
  Let me get you what I owe you.
  It was this right?

  She pushes a puch full of caps to you.

  KATYA
  And, and...
  I know I'm forgetting something.

  Her eyes open wide.

  KATYA
  The gun! Thats right the gun!
  Let me go get it, I'll be right back.

  She gives PETER another deep hug before taking him by the
  hand and running back to their humble home.

  DELVIN
  You did good.

  He smiles. something tells you thats all you're going to get
  from him.

  DEVLIN
  I'm going to make sure PETER'S not left alone while KATYA
  gets you the rifle.

  He turns around following KATYA and PETER. His shoulder's
  unclenched in a way you haven't seen before.
#+end_src

From here the party will be given a few seconds of respite
to enjoy the accomplishment of completing the job before the
collapse comes.

#+begin_src fountain
  The world starts to shake. A violence you haven't
  experienced before. It quickly surpasses the last tremor,
  showing no signs of abating.

  The people around you growing increasingly concerned as it
  becomes clear that the tremor isn't going away. A chunk of
  concrete falls from the ceiling crushing a nearby vendor's
  stall. Panic sets in, people begin running in all directions
  trying to take cover from the debris and get their loved
  ones to safety.

  In the bustle of people, one woman stands unconcerned. You
  catch her gaze and she gestures to your right. Following her
  gesture you see a man in a suit casually reading a
  newspaper.

  He bounces to his feet, putting the newspaper down on the
  bench.

  AEON
  Having fun yet?

  A large piece of concrete detaches from the ceiling and
  crushes HONOLULU HAWAIIAN'S BAR into a heap of debris and
  twisted metal.

  AEON
  I mean they're not.

  A large crack begins forming underneath $(random party
  member)'s feet.

  You jump to one side as the crack in the earth opens up into
  a crevice.

  Peering over the edge reveals a great white void. A
  bottomless unending expanse of nothing. You jump back as the
  split in the world begins to expand consuming several
  buildings. People begin to fall in, as it violently expands
  through the DMZ.

  AEON
  That's my cue.

  The man turns toward the expanding fracture in the world.
  Glancing back at the party.

  AEON
  I've been thinking.
  You can call me AEON.
  I've always had a flare for the dramatic.

  The man smiles before turning back to the void.

  AEON
  Be seeing you...

  With a cavalierness in stark contrast to the crumbling
  world around you. He jumps into the void, falling quickly
  out of view.
#+end_src

Party should maybe roll a will save here to panic.

The party can now do whatever they please, the course of the
collapse has been set. Eventually they will fall in hurtling
toward THE END.

#+begin_src fountain
  You tumble into the void, screaming as you fall head over
  heals into the blinding light. The fissure you fell through
  quickly fading from view. With no landmarks to guide you,
  you lose all sense of direction.

  In some direction, in the distance a small black spec. You
  fixate on it, the only thing that stands apart in this
  expanse of nothingness.

  It begins to grow, slowly at first, but soon it becomes
  noticeable. Rapidly, it starts to eat away at the white void
  , until there's more darkness than light.

  The lightness quickly shrinking into a spec, the only
  remnant of the world you came from, until it is not.

  And you are gone.
#+end_src
