* Dwayne
With the rebirth of the metro once again, the party will be
given the opportunity to change their characters without
removing their memories.

From there they will be told by AEON that it's they day of
the assassination of DWAYNE THE IRAQ JOHNSON and that they
need to prevent his death, because the ensuing chaos
accelerates the destruction of the world.

Aeon has the power to transfer a PC's consciousness into
another body which is how changing character's will be done
between collapses.

#+begin_src fountain
  # New Beginnings

  INT. NONDESCRIPT INN ROOM - MORNING

  Awakening in the inn room you've called home for longer than
  you can remember. You come to a seat on the edge of your
  bed. The sweat that covers your body makes you think that it
  was a nightmare, but the vivid reality of your screams
  echoing silently into that horrible white void tell another
  story.

  Staring at the door to your room, it seems to stare back at
  you, asking

  THE DOOR
  What story do you hope to find when you open me?
  After all, I am a door you've opened many times before, and
  a door you will open many times to come.

  Doubt is a creeping feeling, slowly embedding itself into
  the deepest recesses of your mind. What if, these familiar
  walls are no longer so familiar? That maybe, one day, you
  will close your eyes and the next time you open them you are
  a stranger in your own home. a stranger, in your own body.
  You look back at the door.

  THE DOOR
  (taunting you)
  Look in the mirror.
  and tell me.
  what do you see?
#+end_src

*** Characters
- Aeon
- Dwayne
- Jesse
- Maria (Blue Shoes)

*** Locations
- Mayor's Office
- Crane Control Room
- Town Hall
- The Great Library
- Anomaly Field
*** Steps
**** Orientation
Having established their new identities the PC's will exit
their lodgings to find the DMZ bustling with activity. From
the commotion they find out that its the day before DWAYNE'S
assassination.

Soon after they will be greeted by AEON who will relay to
them what little they know about the collapse. AEON'S
knowledge of how/why the collapses are happening is
limited to:
- Seem to come after certain pivotal sociological events
- When AEON is consumed, time is brought back to one of the
  pivot events (death of DWAYNE in this case)
- Someone is orchestrating the events through acolytes
- Preventing the event, prevents the collapse

From this they will come to the conclusion that DWAYNE needs
to live and they're the only ones that can stop it.

#+begin_src fountain
  ## Orientation

  EXT. LOCAL INN - MORNING

  You stumble your way out of the inn, still reeling from
  the twist of fate. You are greeted by the fervent bustling
  crowd of DMZ residents going about their day. Their faces
  display not fear or dread, but excitement and purpose. You
  haven't seen the DMZ this buzzing since...

  $(random party member) a shoulder CRASHES into yours, you
  lurch, so does he. Confusion, in his right hand a stack of
  paper. You look into his face, Anger, his left hand clenches
  into a fist. You brace for a fight. The man looks to his
  right hand, catching a glimpse of something on the pages his
  face softens, fist un-clenches. He looks you in the eye.

  POSTER MAN
  I am so sorry.
  Please excuse my clumsiness.

  He extends out his hand to shake yours, his apology genuine.

  Satisfied, he moves past you and up to the wall behind you.
  Pulling a roll of tape from his pocket he goes to work
  putting up one of his posters. As he's finishing up, he
  looks back to see you gazing, he smiles and gives you a
  polite nod before walking off, posters in hand.

  _DWAYNE!_

  ONE NIGHT EVENT

      AT

  THE JSA

  midnight tonight!
  free admission
#+end_src

From here either the party will infer that time has somehow
gone back to the day of DWAYNE'S death or they will ask a
passerby what day it is. This is where AEON will enter to
explain what they know and give them the "quest" to prevent
DWAYNE'S murder.

#+begin_src fountain
  From across the street a gruff man sitting alone on a bench
  catches your attention. Upon seeing you, he springs to his
  feet, a piece of his shirt catching on a nail and ripping
  off another patch from the already patchy garment. He
  doesn't seem to mind.

  Quickly, he make's his way over to you, practically shaking
  with excitement.

  AEON
  (In a garish tone)
  Hello, hello, hello
  Welcome...

  The man goes in for a quick awkward hug with each of you.
  He smells funny.

  AEON
  Interesting times don't you think?
  (glancing at the poster of DWAYNE)
  A classic, but always fun to unravel.

  THE PARTY
  (Asking what they mean)

  AEON
  DWAYNE of course! Who else?
  He's *was* dead, now he's just *soon* to be dead.
  And that's where you come in.

  THE PARTY
  (Asking what they're supposed to be doing)

  AEON
  Well we're trying to move DWAYNE from the *soon* to
  be dead
  category and put him in the *not* going to be dead
  category.
  Otherwise...
  (gazing off a thousand yards away)
  You know...

  THE PARTY
  (Asking why AEON can't solve it themselves)

  AEON
  I mean, obviously I can't be in two places at once,
  wait...
  (Looking quizzically off to the side)
  No, definitely can't do that.
  I have other thing that need attending to.
  You know, a coup or something, It always tries
  something different.

  THE PARTY
  (Asking what "It" is)

  AEON
  I don't know, but it's definetly something. Usually it's an
  acolyte with a bomb strapped to their chest or a gun to
  someone's head. They ramble on about chaos, but I've never
  gotten anything more out of them.

  THE PARTY
  (Asking how they're supposed to know what to do)

  AEON
  You were there weren't you? What do you remember about it?
  [[If member's of the party weren't in the last season]]
  /* At least you three/four [[if ders is present]] were. I*/
  /* don't know what the rest of you were doing... */

  THE PARTY
  (regails some of their memories of DWAYNE'S death)

  AEON
  Well there you go!
  (looking at their watch)
  Look, I gotta go. You're going to do great!

  AEON begins to back away from the conversation.

  AEON
  Just remember. Don't fuck it up!

  AEON turns and runs into the crowd of people and you quickly
  lose sight of them.
#+end_src

**** A Future Murder

From here the party will begin to unwravel the mystery of
DWAYNE'S assassination. The actual plot of which is:

Two men and one woman have traveled from various parts of
the metro, each carrying a piece of a sniper rifle on their
person, smuggling it from station to station. Upon arrival
at the DMZ they bribed a crane operator (one of few
individuals with clearance to go up to the operating booth
which lies in neutral territory) for his pass. Using the
pass one of the assassins, brought the disassembled rifle up
to the booth where it was assembled and placed on a desk in
the middle of the room (It's intended firing position). With
the rifle in place, the assassin zeroed the rifle and
removed a single glass pane from the booth window that he
would be firing through, placing the panel in one of the
desk drawers. With the firing position established, the
rifle was disassembled and carried back out. On the day of
the assassination, the three assassins will make their way
up to the operator's booth, dispatching the guard in the
process, assemble the rifle and kill Dwayne. After killing
him they will disassemble the rifle, giving each of the
assassins back their case and make their way out of the DMZ
in separate directions.

The three clues for the operator room being a sniper's nest
are:
- Two small rectangular dustless spots on the table about 10
  inches apart with one larger rounder dustless spot about
  two feet back about the center line between the smaller
  spots (imprints left by the sniper rifle stock and the
  bipod during zeroing)
- The cutout pane from the window facing the JSA that lines
  up with the imprints on the desk. (firing port)
- A single military grade rifle round rolled under one of
  the desks (from one of the cases)

Each of the assassins will have a passport on their person
with stamps from each of the stations along their path.
Eaching having taken different paths, one passport isn't
enough to get a location. With all three passports, it will
become clear that all three assassin's came from the same
general area.

#+begin_src fountain
## A Future Murder
#+end_src

****** A Trip to the Mayor's Office

The party, upon realizing they can't get into the operator's
booth without authorization will have to speak with the
mayor, Jesse. Jesse is an idiot and will blow them off at
every turn either by regaling stories of his prowess at all
things or harassing Maria. When they finally say that Dwayne
is going to be assassinated Maria will push Jesse out and
begin to question the party as the true power of the mayor's
office.

#+begin_src fountain
  ### The Mayor and her Stooge

  INT. MAYOR'S OFFICE SECRETARY'S OFFICE - MIDDAY

  You enter into a secretary's office, it's sleek wood
  paneling and finely varnished furniture separate it from
  other places in the DMZ. Along the left wall, a row of
  cushioned chair leading toward the back and butting up
  against two wood sliding doors with large frosted glass
  windows. The blurry outline of a man is present in the
  glass. Tucked into the right corner a secretary is typing
  away at her workstation. The window blinds behind her are
  open, the bustle of the DMZ visible.

  THE PARTY
  (Makes there way into the room)

  MARIA
  (Glancing up from her computer)
  Hello, how can I help you?

  THE PARTY
  (Asking to see the mayor)

  MARIA looks through a calendar on her desk.

  MARIA
  I am so sorry, It seems that the mayor is busy at the
  moment. Can I make an appointment for you in, say, a few
  weeks?

  MARIA looks up at you expectantly.

  From behind the doors to the office you hear a voice yell
  out.

  MAYOR JESSE
  (excitedly)
  OOOOOOHHH, so close!
  Blue Shoes! That was, like, one of the best ones yet!
  You shoulda seen it!

  The figure behind the glass excitedly makes his way to the
  door, sliding it open just enough to stick his head through.

  MAYOR JESSE
  BLUE SHOES! DID YOU HEAR ME!
  (Spotting the party)
  Oh, hey man.

  MARIA sighs, looking back at the party.

  MARIA
  Let me introduce you...

  grabbing a notebook and some folders, she leads you to the
  doors. Sliding them open wide.

  MARIA
  Mr. Mayor, These gentlemen are here to speak
  with you.

  MARIA steps to the side gesturing you inside. Sliding the
  doors closed behind you, she takes a seat in the corner of
  JESSE'S office and begins taking notes. Blinds shut tight,
  the only light in the office is the warm glow of the
  incandescent light in the softly spinning ceiling fan.

  MAYOR JESSE
  You came to see, me? I mean like ya you did, I would come
  see me too! I'm, like, the best, man.
  Have you ever, like, played tiny golf? It's like regular
  golf, except, you know, tiny.
  Here, here, let me show ya.

  JESSE reaches out, grabbing $(random party member) and
  guiding them to the right side of his office. Where he has
  an overturned mug in one corner as a makeshift putting
  green. A dozen or more golf balls have pilled up in the
  corner having veered wildly off course.

  MAYOR JESSE
  (Lining up his putter)
  I'm like the best at it man. Like hole in ones every time.
  (Standing back)
  You know, like, I played a whole eight course game with that
  commie bastard ZALINSKY. I won of course, like, why wouldn't
  I.
  (Lining up his putter)
  This is obviously way too difficult for a beginner such as
  yourself.
  (Standing back)
  Actually why don't you putt, and you'll see how hard it is
  and how, like, amazing I am.

  He hands you the putter and stands to the side, arms crossed
  and a smug expression on his face.

  @$(selected party member)
  (sinks/doesn't sink the putt)

  MAYOR JESSE
  /* If pc sinks the putt */
  That's just like beginner's luck man, here watch a pro.
  /* if the pc doesn't sink the putt */
  See man, I'm just like the best, here watch a pro.

  JESSE hardly lines up his putter before clumsily whacking the
  golf ball hard into the corner, missing the mug completely.

  MAYOR JESSE
  You're like messing up my vibe standing so close to me, man.
  I can't putt like this, with you like, breathin down my
  neck, man.

  Visibly frustrated JESSE collapses into his office chair.

  THE PARTY
  (Mentioning MARIA in any way)

  MAYOR JESSE
  OH, Blue Shoes! She's like the best man.

  MARIA winces at the name. JESSE leans in attempting to whisper
  to you.

  MAYOR JESSE
  Isn't she like, soo hot, man. I mean, like, look at her.

  JESSE'S gaze makes its way all the way down MARIA'S body,
  until settling on her shoes, his mind salivating at the
  thought. Her disgust overt to everyone but JESSE.

  MAYOR JESSE
  She's, like, totally, my girlfriend man.

  MARIA gives JESSE an aggressively fake smile and rolls her
  eyes.

  MAYOR JESSE
  That's how I know she like, likes me man.

  THE PARTY
  (Mentioning the assassination of DWAYNE)

  MARIA stops taking notes, and for a moment the room is
  silent. The silence is broken by JESSE scoffing in disbelief
  at what he's hearing.

  MAYOR JESSE
  That's like, just your opinion man. Like, that's the dumbest
  thing I have *ever* heard. You come in hear, into my home,
  my humble abode, and accuse me of, like, not being a good
  mayor, man?

  He spreads his arms wide, putter still in hand.

  MAYOR JESSE
  You know what man, I think, like, you're like a saboteur or
  something. Come to ruin me, that's totally like treason man.

  JESSE'S rant is interrupted by MARIA, appearing by his side,
  a loose stack of papers in hand. She puts a gentle hand on
  his shoulder, handing him the stack of papers with a well
  practiced smile. He deflates at her touch.

  MARIA
  JESSE, don't you think you should be practicing for your
  ,*big* speech before the event tonight. Everyone's going to
  love it. Why don't you go practice in front of the mirror? I
  know how much you love that.

  MAYOR JESSE
  You know what, you're right BLUE SHOES, these people, like,
  don't deserve my attention. They're just like posers man.

  She begins to lead JESSE out of the office, nodding along
  with him, slipping $(random party member) a serious look.
  She gently nudges JESSE out of the office, giving him a
  another deft smile. JESSE lets out another stream of
  expletives at you before MARIA slides the doors closed.
  Letting out a sigh of relief, she walks back around the
  desk, leaning against it with both hands. The demure
  secretary has dissapeared and something else has taken its
  place

  MARIA
  What the fuck did you just drop at my doorstep?

  THE PARTY
  (Reiterating that DWAYNE will be assassinated)

  MARIA
  I need you to tell me *exactly* how you know this is going
  to happen, and it better be pretty damn convincing.

  THE PARTY
  (Explaining how they know, roll charisma)

  MARIA
  Fuck...

  She takes a seat in JESSE'S chair, leaning her head against
  clenched hands. She takes a break, collecting herself.

  MARIA
  Alright, I need evidence. Getting the event shut down is
  above even me, but if you can get me who, when, and how. I
  can *maybe* convince JESSE and we can prevent this disaster.
  What do you need from me?

  THE PARTY
  (Asking for access to the operator's room)

  MARIA
  Done.

  She picks up the phone dialing as she does so. Through the
  line you can hear the faint voice of a man.

  MARIA
  MARTIN, I have a few gentlemen hear that need access to the
  operator's booth.
  (beat)
  Yes, on my behalf. Ask for...

  Pulling her face away from the phone., she snaps her fingers
  at the party.

  MARIA
  One of your names...

  THE PARTY
  (giving one of their names)

  MARIA
  $(name given).
  (beat)
  Wonderful, Thank you M...
  (beat)
  Should be same time this Sunday. Wait..
  You're not still mad DAVIE took all your money are you?
  (beat)
  We *told* you, you can't out bluff DAVIE, MARTIN.

  You can hear the sound of a second man laughing in the
  background of the phone call. A wry smile forms on MARIA'S
  face, the first genuine smile you've seen from her.

  MARIA
  Look, MARTIN, I have to go.
  Make sure they get what they need.
  Thank you.

  She hangs up the phone, looking back at the party.

  MARIA
  You're good to go.
  MARTIN and CORIQ will get you up there.
  Do **NOT**, go past the booth into red territory. I don't
  want another mess to clean up.
  Anything else?

  THE PARTY
  (Asking about the BLUE SHOES name)

  Her face contorts at the mention of the name.

  MARIA
  I made the mistake of wearing a pair of blue shoes on my
  first day. JESSE seems to have taken a liking to them. Shame
  really, I liked those shoes...

  Her gaze drifts, lost in thought.

  /*
  If the party asks what happened to them

  MARIA
  I burned them.

  She says matter-of-factly.
  ,*/

  VINCENZO
  (Being a chauvinist to MARIA)

  MARIA'S face is filled with disdain. She looks to the rest
  of the party.

  MARIA
  Muzzle your mutt before I do it for you.

  VINCENZO
  (Continuing to be a chauvinist to MARIA)

  As you continue your misogynistic diatribe, MARIA quietly
  picks up her phone, speaking a few words to someone, her
  words inaudible over your ranting.

  It's not a minute later that the doors slide open and in
  steps a hulking behemoth of a man. VINCENZO barely
  reaching his chin. Closing the door behind him.

  CHARLIE
  Ms. MARIA.

  MARIA
  CHARLIE.

  MARIA darts her eyes to VINCENZO. Action is immediate.
  CHARLIE grabs VINCENZO'S head with one hand, his wrist in
  the other before slamming his head hard against the desk,
  breaking VINCENZO'S nose.

  MARIA walks around the table, taking a half seat against the
  table next to VINCENZO'S head, facing CHARLIE.

  MARIA
  How's Janine, CHARLIE?

  CHARLIE
  Oh wonderful, Ms. MARIA.
  She wanted me to thank you for the skirt you got her.

  MARIA
  Well, she can thank me herself over dinner.
  Saturday at my place.
  I'll get you a sitter.

  CHARLIE
  We would love that, Ms. MARIA.

  They give each other a warm smile, while VINCENZO struggles
  helplessly under CHARLIE'S iron grip.

  MARIA
  Do you think he's learned his lesson?

  CHARLIE leans in next to VINCENZO, contorting his wrist to
  it's breaking point, the pain excruciating.

  CHARLIE
  Have you?

  VINCENZO
  (Agreeing)

  MARIA
  Thank you CHARLIE.

  CHARLIE releases VICENZO from his grip, and quietly slips
  out of the office. MARIA sits back in the office chair.

  THE PARTY
  (Asking why JESSE is kept around)

  MARIA
  He's the mayor. At least on paper.

  THE PARTY
  (Asking what she does)

  MARIA
  I keep things moving.
  A few more food stamps, a bit more housing assistance
  Small things, incremental, but they add up.
  (beat)
  Plus, a man like JESSE can open doors that are normally
  closed to me. As long as you handle his more...
  grating...
  behavior.

  THE PARTY
  (Making the gesture to leave)

  MARIA
  Report back when you find out whats going on. I'll see what
  I can do about increasing DWAYNE'S security detail in the meantime.
#+end_src
