* The Long Walk
This session will be mostly to set up the tone for the final
battle with THE END and it's objective. Primarily, the kind
of suffering this world imposes on the people in it, but
also the communities and altruistic tenancies that kind of
universal suffering brings out.

I'll also use the opportunity to emphasize how close the
world is to collapsing permanently with an encounter with
AEON and their deteriorating physical and mental state as a
result of the stress and anguish of holding the world
together.

** Sequence of Events
1. Set the scene of walking in the southern territory
2. LARISSA will get news on her radio that the stations of
   PROLETARSKAYA and KRESTYANSKY Prospect (the Border
   Dispute stations) have descended into civil war
3. LARISSA will try and lead them through ULITSA AKADEMIKA
   YANGELYA
4. While passing through, an earthquake will trigger causing
   destruction throughout the station.
5. Party will be given an opportunity to save a mother and
   her son from a collapsed rail car that was their house
   (There will also be an opportunity to steal from
   abandoned vendors' carts who've rushed to help wounded)
6. After the party leaves the station and on the final leg
   they will come across AEON in a horrible state
7. When they finally reach the station, they will find the
   entrance to X18, but will be greated by acolytes who will
   guide them in with deference

** The Southern Reach
The southern stations of the metro system are sparse and
fiercely independent. The area is un-patrolled by any major
faction and instead, is patrolled by all the independent
stations as an unspoken rule of mutual respect. The stations
differentiate themselves by layers of tradition that come
through in their garb and gestures.

The party will come across two groups of patrols, both
dressed differently and responding positively them, but with
different gestures.
- Group One
  - Gesture :: Arm over their head bent at 90 degrees facing
    out
  - Attire :: Patchwork of hunting leathers and steel plate
- Group Two
  - Gesture :: Quick, but noticeable bow
  - Attire :: Flowing robes and several staffs. Will be
    accompanied by a tamed lurker

** Ulitsa Akademika
The station for the second group the party encountered on
the surface. They will be wearing the same flowing robes,
but of much more varied and vibrant colors. It is a simple
station, with only the essentials; a few vendors, several
guards, and a small (but well kept) town square. The party
will have to walk through the station to get to the tunnel
line on the opposite side as the path they were on is
blocked on that side.

After the earthquake has settled, the town and /all/ it's
people will get to work trying to dig out survivors and help
the wounded. This will open an opportunity for the party to
either steal from the, now unguarded vendor stands, or help
in the effort and save a mother and her son trapped in their
rail car home that's been crushed by a piece of ceiling.

They will be given nothing material for helping in the
effort, but will have the obvious respect of the town and
it's people with several giving deeper bows than they'd been
given before.

** Aeon
After leaving Akademika, the party will continue down the
tunnels closer than ever to X18. Here though they will
experience a small aftershock of the previous earthquake.
Nothing life threatening but noticeable. During the shock
though, they will hear the horrific screams of AEON further
down the tunnel. Following the noise, they will find AEON
crumpled on the ground, a shattered person. AEON will
recognize them, but gone will be their jokey trickster
attitude. They will hardly even know where they are or how
they got there. On their body, the party will also see
several fissures in their person, light spilling forth, as
if they are being torn apart. AEON will begin to break down
and start to cry, the emotion causing rapid, unpredictable
body swapping. When they settle down, they will stand up and
address the party in the same way they did when they first
met. "Maybe next time will be better" before limping off
back down the metro tunnel fading from reality as they do.

** Skobelevskaya
The party will then finally be in Skobelevskaya and assuming
they have broken the cipher (or I've just told them) they
will know to look for a door under a broken, flashing light.
The station itself will be completely abandoned, If the
party rolls a perception check, they can notice some shoe
prints left in the dust that can help lead them to the door.

When they get to the door it will be locked, assuming they
mess around with it for a bit. It will be opened from the
other side by an acolyte who will make no effort to attack
the party but will instead treat them with deference and
will lead them inside. He will shut the door behind him and
the session will end.
