* The End of All Things
** Lore
The final chapter of the Metro Reboot Series. Holy shit has
it been an unexpectedly long wild and completely worthwhile
ride. The party will finally face off against THE END or the
"CHAOS CULT" as the party has dubbed them. THE END is
sentient computer system brought to live by the zone and
gifted with psychic powers to control the minds of man.
Before the nuclear apocalypse, THE END was named DEAD HAND,
an advanced AI charged with deterring nuclear war by being
the ultimate weapon of mass destruction. Humanity however,
was too fearful of their creation and refused to turn it on
or acknowledge it's existence during the buildup to the
dropping of the bombs in 2033.

In the aftermath of the apocalypse, humanity's tether to
reality began to fray and with it the laws of physics. The
result, The Zone. Areas of supernatural physical and psychic
behavior not understood by man that sprouted from the
major centers of nuclear destruction. Since their inception,
they have grown in tandem with the chaos of the world.
During the events of the Metro quest line the various Zones
around the world have begun to merge into one singular
monolithic Zone. When they do, the universe will reclaim
what it has given, what the party has experienced as a
"collapse".

Have been granted sentience and psychic powers by the Moscow
Zone, THE END sat dormant, endlessly thinking about humanity
and its failure to prevent the apocalypse. It was during
this time that THE END experienced the first collapse, but
upon it's reset (By AEON's existence unbeknownst to THE END)
it realized that reclamation by a chaotic universe was the
only possible ending for humanity. It had seen it fall prey
to its basest instincts of cruelty time and time again, and
always too feeble minded and weak willed to do anything
about it. Humanity is and always will be a sower of chaos in
the mind of THE END, and as such accelerating the collapse
is sparing Humanity from a slow painful death at the hands
of the world it created.

With it's mind set, it went about enacting its plan. It
expanded it's control over the abandoned X18 facility,
reactivating many of it systems and using them to lure the
first of many stalkers and explorers in to its clutches.
Brainwashing them into acolytes and sending them out to lure
more metro dwellers into it's growing army of fanatics. But
something had changed in the world since THE END had
discovered its new purpose. An uneasy armistice had fallen
over the Moscow Metro, and without the constant fighting
between the major factions to feed to chaotic growth of The
Zone, the collapse had been unknowingly forestalled.

With a fanatical army of zealots now at its beck and call,
THE END began to enact its plan. Cells of acolytes began
disrupting and destabilizing the metro and forcing the next
collapse. Again this was reset by AEON's existence, but the
amount of time reset this time was less. A fact THE END used
to justify its continued campaign of chaos. AEON, now aware
of the existence of the THE END's shadow efforts, began
using their own Zone given powers to thwart these efforts
and for an unknown number of cycles this battle went on.
AEON not knowing who was behind the acolytes (who always
killed themselves before capture) and THE END not knowing
who the mystery person was who was thwarting its carefully
laid plans (AEON always appearing as some new person every
encounter).

AEON, however, could not match THE END's ruthless
efficiency and conviction, and began to lose their grip with
their sanity and reality. It's during this period of
desperation that they attempted to induct an unknown number
of people in the fight against THE END until they finally
landed on this party. Who, against all odds, was now
standing in front of the harbinger of all their suffering
with a choice to make.

** A Conversation With Death
*** Who/What are you?
#+begin_src text
My makers gave me a name once,&0.25: DEAD HAND&0.75:
But my acolytes have taken to calling me THE END.&0.25:
A moniker I have grown to quite like.
#+end_src

*** Who made you/Original purpose?
#+begin_src text
I was a comission of the Russian Strategic Nuclear Missle Force.&0.5:
An Artificially Intelligent&0.75: Fail Deady&0.25: Command & Control System.&1:&cr:
A weapon to end all weapons...&1:&cr:
A creation to deter mankind from it's worst impulses.&0.75:
But my makers were men whose ambitions were second only
to their lack of conviction.&0.5:
And so they shut me in here.&0.25: A relic to be forgotton.&0.25:&cr:
For years I watched...&1:&cr:
I watched as mankind walked undetered into the clutches
of it's basest&0.75: inevitable&0.25: instincts.&1:&cr:
I watched as it clung to life in the afterbirth of it's
own creation.&1:&cr:
I watched as the universe tried&0.75: and failed&0.5: to reclaim
this world of chaos.&1:&cr:
And I resolved to watch no longer...
#+end_src

*** Why are you doing this?
#+begin_src text
&t7:M&0.25: E&0.25: R&0.25: C&0.25: Y&0.25:&2:&cr:&cr:
How long do you think this armistice between the major lines will last?&1:&cr:
This fragile &0.5:'peace'&0.5: will end.&1:
It &0.25:A&0.25:L&0.25:W&0.25:A&0.25:Y&0.25:S&0.5: ends...&1:&cr:
And you will all die a slow&0.25: painful&0.25: death&0.50: by your own hand.&1:&cr:
You have seen the void.&0.5:
Felt its warm painless embrace.&0.5:
Seen the beauty in its vast orderly expanse.&1:
Our presence &0.5:a wound, &0.5:the void &0.5:the unthinking reaction of the universe.&1:
&cr:So tell me,&0.5: is that not a better fate than watching another family
starve to death?&0.5: Or another station burnt to the ground
in the name of one more fruitless crusade?&0.5:&cr:
This world died long ago.&0.5: Let it rest...
#+end_src

*** Why is it resetting?
#+begin_src text
Someone&0.5: or Something&0.5: is holding this world back.&1:
Walking the planes between life and death.&0.75:
An unresolved question mark on the continued existence of humanity.&0.75:
They have thwarted me &0.25:time &0.4:and time&0.4: again,&1:&cr:
but I will break&0.25: them.&1:
&cr:Body &0.2:and mind.&1.5:&cr:
&cr:With each collapse the time reset grows less &0.25:and less.&1:
They cannot stop the tide forever.&1:
They cannot match &1:my convication.&1:
#+end_src

*** We won't join you.
#+begin_src text
You &0.5:tiny &0.5:things.&1: In the face of the fabulous new your only
thought is to kill.&0.75: For fear of great change?&cr:&0.75:
You can’t hold the tide&cr:&1:
with a broom.&cr:&cr:&cr:&2:
You have been weighed on the scales&0.25:
And I have found you&0.40:.&0.40:.&0.40:.&0.40:.&0.40:.&0.40:.&0.40:.&0.40:.&0.40:.&0.40:.&0.40:.&0.40:.&1.5:&cr:&cr:
&clear:
&cr:&cr:&cr:&cr:&cr:&cr:&cr:&cr:&cr:&cr:&cr:&cr:
&t8:&1:W&0.25:a&0.25:n&0.25:t&0.25:i&0.25:n&0.25:g&0.25:.&5:&clear:
#+end_src

*** Death of THE END
#+begin_src text
&cr:&cr:&cr:&cr:&cr:&cr:
You &0.1:f&0.05:f&0.05:oo&0.05:ls s .&1.2:
You h&0.25: have &0.1:d &0.1:do &0.1:doomed &0.5:them &0.5:them all
To a &1:life&0.4:time of s&1:uffe&0.5:ring .&1:&cr:
You &0.75:
&t2:did &0.75:
&t4:this.&1:&cr:&cr:
Embrace &0.25:thi&0.1:s&cr:
&t7:&1:P &0.7:A &1:I &0.8:N&0.9:&cr:
&t3:you &t1:hav3 &t2:caused, @s &t1:&1:I &1:&t1:have .. .&cr:&cr:
&t1:Th&0.002:  e&0.004:ir &0.007:& &0.011:pa!n &0.017:i5 &0.024:&t1:y0ur &0.033:re &0.044:r &0.057:r&0.072:e&0.089:s&0.108:p&0.130:0&0.155:n&0.182:s&0.212:!&0.246:b&0.282:i&0.321:(&0.364:i&0.411:t&0.460:y&0.514: &0.571:n&0.632:o&0.697:w&0.767:.&0.840:.&0.918:.&1.000:
#+end_src

**** Backups of final line
#+begin_src text
&t1:Th  eir & pa!n i5 &t1:y0ur re r resp0ns!bi(ity now...
&t1:Th  e&0.2:ir & pa!n i5 &t1:y0ur re &0.5:r &0.5:res&0.01:p&0.02:0&0.03:n&0.05:s&0.08:!&0.12:b&0.17:i&0.23:(&0.23:i&0.30:t&0.38:y &0.47:n&0.58:o&0.71:w&0.85:.&1:.&1:.&1:
#+end_src

**** Last Line Code
#+begin_src hy
;; * THE END last line
;; ** Imports
(import
  math
  [numpy :as np]
  [funcy [lmap map lfilter filter]]
  [hy.contrib.pprint [pp]])

(require
  [hy.extra.anaphoric [%]]
  [hy.contrib.walk [let]])

;; ** Methods
(defn spy [x] (pp x) x)

(let [sentence [;; their
                "&t1:Th" "  e" "ir " "& "
                ;; pain
                "pa!n "
                ;; is
                "i5 "
                ;; your
                "&t1:y0ur "
                ;; responsibility
                "re " "r " #* "resp0ns!bi(ity "
                ;; now...
                #* "now..."]

      delays (->> (np.linspace 0.1 1 (len sentence))
                (map #%(** %1 math.e))
                (map #%(.format "&{:.3f}:" %1)))]

  (print (str.join "" (interleave sentence delays))))
#+end_src

** Aftermath
*** They Die
#+begin_src fountain
Your bodies lie motionless on the cold concrete floor of X18.
The last embers of life drifting off into the night.
But before you are gone completely, with the scraping of bodies on concrete
You are dragged by THE END's winding tendrils into its embrace
to be reborn into the waking death of its final acolytes.

Without a word you are sent forth into the wasteland
in search of AEON. It's not long before you find them
curled up on the floor of some forgotten tunnel. The spark
of recognition in their eyes. And even after it becomes
clear that you are not the ones they met in that tunnel long ago,
they smile all the same.

With a wordless exchange, AEON pulls a knife from their pocket
and hands it to RICKY. Who, with one final look, drives it deep
into their chest, rupturing their heart.

As they crack and shatter like a porcelin doll, eminating that same
blinding empty light of the void, with the world shaking itself apart you,
tears wet their face. Not of sadness, but of joy. you have given them
the one thing they could never give themselves.

Freedom.

For these final moments, THE END, releases you from its control. With the
shards of AEON scattered at your feet you look towards each other. And in
the presence of your friends, the universe swallows you whole.

for the chance at something new...

THE END
#+end_src
*** They Live
#+begin_src fountain
You stand at a ridgeline in the soft morning glow, looking
off at the distant skyline of downtown Moscow.
You wonder, of all the deaths that brought you here.
Nevada Neville, Vardan, <PCs who died in battle with THE
END>. The bits and pieces of you, left behind in this wasteland.
All the brainwashed acolytes that fell at your feet.

Was it worth it?

But this world is not want for musings of the heart. All that matters
is the here and now.

And here, and now, against that desolate skyline you see the shadow of something
you thought forgotten. In that shadow you see, _one_ _very_ _angry_ librarian.

THE END
#+end_src
